@pragma('vm:entry-point') @pragma('vm:never-inline')
String risky(int n) => n == 0 ? 'value=safe-default' : 'value=' + (100 ~/ n).toString();  // FIXED
@pragma('vm:entry-point') @pragma('vm:never-inline')
String caller() => 'result -> ' + risky(0);
// NOTE: _sankofaManifest() + the dyn-module entry are generated by the CLI from
// the diff's app-scoped changed set (make_and_apply_patch.sh) so the patch is a
// single self-contained file the device boot hook reads (no loose .names).
